config/routes.rb
Rails.application.routes.draw do

  # Orders
  get 'order_done', to: 'orders#done'
  get 'order_download', to: 'orders#order_download'
  get 'update_detail', to: 'details#update_detail_get'
  # API
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post 'login', to: "authenticate#login"
      get 'orders', to: 'authenticate#orders'
      post 'orders', to: 'authenticate#order'
    end
  end

  # Staff Login system
  get "login", to: "staffs#login"
  post "validate", to: "staffs#validate"
  get "logout", to: "staffs#logout"
  get "dashboard", to: "orders#unsolve"

  resources :details
  resources :orders
  resources :products
  resources :staffs
  resources :departments
  resources :customers
  root "staffs#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order
  # belongs_to :product
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :authenticate
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  def update_detail_get
    detail = Detail.find_by(id: params[:detail_id])
    detail.name = params[:name]
    detail.price = params[:price]
    detail.qty = params[:qty]
    detail.remark = params[:remark]

    respond_to do |format|
      if detail.save
        format.html { redirect_to order_path(params[:order_id]), notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to order_path(params[:order]), notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      # params.require(:detail).permit(:order_id, :name, :qty)
      params.require(:detail).permit(:order_id, :name, :qty, :price, :remark)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for(detail) do |f| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :qty %>
    <%= f.number_field :qty %>
  </div>

  <!-- <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :remark %>
    <%= f.text_field :remark %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Details</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Product</th>
      <th>Qty</th>
      <!-- <th>Price</th>
      <th>Remark</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.order %></td>
        <td><%= detail.product %></td>
        <td><%= detail.qty %></td>
        <!-- <td><%= detail.price %></td>
        <td><%= detail.remark %></td> -->
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @detail.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @detail.product %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @detail.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= @detail.price %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @detail.remark %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>